blog/urls.py
from	django.urls	import	path
from	.	import	views
app_name	=	'blog'
urlpatterns	=	[
				#	post	views
				# path('',	views.post_list,	name='post_list'),
                path('',	views.PostListView.as_view(),	name='post_list'),
				path('<int:year>/<int:month>/<int:day>/<slug:post>/',
									views.post_detail,
									name='post_detail'),
				path('<int:post_id>/share/',
									views.post_share,	name='post_share'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',	include('blog.urls',namespace='blog')),
]

urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models

# Create your models here.
from	django.db	import	models
from	django.utils	import	timezone
from	django.contrib.auth.models	import	User
from	django.urls	import	reverse

class	PublishedManager(models.Manager):
    def	get_queryset(self):
		    return	super(PublishedManager,self).get_queryset().filter(status='published')

class	Post(models.Model):
				STATUS_CHOICES	=	(
								('draft',	'Draft'),
								('published',	'Published'),
                                				)
				title	=	models.CharField(max_length=250)
				slug	=	models.SlugField(max_length=250,unique_for_date='publish')
				author	=	models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
				body	=	models.TextField()
				publish	=	models.DateTimeField(default=timezone.now)
				created	=	models.DateTimeField(auto_now_add=True)
				updated	=	models.DateTimeField(auto_now=True)
				status	=	models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
				objects	=	models.Manager()	#	The	default	manager.
				published	=	PublishedManager()	#	Our	custom	manager.
				def	get_absolute_url(self):
								return	reverse('blog:post_detail',args=[self.publish.year,self.publish.month,self.publish.day,self.slug])

class	Meta:
    		ordering	=	('-publish',)

def	__str__(self):
			return	self.title


class	Comment(models.Model):	
				post	=	models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
				name	=	models.CharField(max_length=80)	
				email	=	models.EmailField()	
				body	=	models.TextField()	
				created	=	models.DateTimeField(auto_now_add=True)	
				updated	=	models.DateTimeField(auto_now=True)	
				active	=	models.BooleanField(default=True)	
				class	Meta:	
								ordering	=	('created',)	
				def	__str__(self):	
								return	'Comment	by	{}	on	{}'.format(self.name,	self.post)	

blog/forms.py
from	django	import	forms
class	EmailPostForm(forms.Form):
				name	=	forms.CharField(max_length=25)
				email	=	forms.EmailField()
				to	=	forms.EmailField()
				comments	=	forms.CharField(required=False,widget=forms.Textarea)

from	.models	import	Comment
class	CommentForm(forms.ModelForm):
				class	Meta:
								model	=	Comment
								fields	=	('name',	'email',	'body')

blog/views.py
from django.shortcuts import render

# Create your views here.
from	django.shortcuts	import	render,	get_object_or_404
# from phonenumbers import region_code_for_country_code
from	.models	import	Post,Comment
from	.forms	import	EmailPostForm,	CommentForm
from	django.core.paginator	import	Paginator,	EmptyPage,PageNotAnInteger

def	post_list(request):
        object_list	=	Post.published.all()
        paginator	=	Paginator(object_list,	3)	#	3	posts	in	each	page
        page	=	request.GET.get('page')
        try:
                posts	=	paginator.page(page)
        except	PageNotAnInteger:
        #	If	page	is	not	an	integer	deliver	the	first	page
                posts	=	paginator.page(1)
        except	EmptyPage:
        #	If	page	is	out	of	range	deliver	last	page	of	results
                posts	=	paginator.page(paginator.num_pages)
        
        return	render(request,'blog/post/list.html',{'page':	page,'posts':	posts})


def	post_detail(request,	year,	month,	day,	post):
				post	=	get_object_or_404(Post,	slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
				#	List	of	active	comments	for	this	post
				comments	=	post.comments.filter(active=True)
				new_comment	=	None
				if	request.method	==	'POST':
								#	A	comment	was	posted
								comment_form	=	CommentForm(data=request.POST)
								if	comment_form.is_valid():
												#	Create	Comment	object	but	don't	save	to	database	yet										
												new_comment	=	comment_form.save(commit=False)
												#	Assign	the	current	post	to	the	comment
												new_comment.post	=	post
												#	Save	the	comment	to	the	database
												new_comment.save()
				else:
								comment_form	=	CommentForm()	
				return	render(request,'blog/post/detail.html',{'post':	post,																			'comments':	comments,
																			'new_comment':	new_comment,
																			'comment_form':	comment_form})



from	django.views.generic	import	ListView

class	PostListView(ListView):
				queryset	=	Post.published.all()
				context_object_name	=	'posts'
				paginate_by	=	3
				template_name	=	'blog/post/list.html'


from	.forms	import	EmailPostForm
from	django.core.mail	import	send_mail
def	post_share(request,	post_id):
				#	Retrieve	post	by	id
				post	=	get_object_or_404(Post,	id=post_id,	status='published')
				sent	=	False
				if	request.method	==	'POST':
								#	Form	was	submitted
								form	=	EmailPostForm(request.POST)
								if	form.is_valid():
												#	Form	fields	passed	validation
												cd	=	form.cleaned_data
												post_url	=	request.build_absolute_uri(post.get_absolute_url())
												subject	=	'{}	({})	recommends	you	reading	"{}"'.format(cd['name'],	cd['email'],	post.title)
												message	=	'Read	"{}"	at	{}\n\n{}\'s	comments:{}'.format(post.title,	post_url,	cd['name'],	cd['comments'])
												send_mail(subject,	message,	'admin@myblog.com',	[cd['to']])
												sent	=	True
				else:
								form	=	EmailPostForm()
				return	render(request,	'blog/post/share.html',	{'post':	post,'form':	form,'sent':	sent})

blog/templates/blog/base.html
{%	load	static	%}
<!DOCTYPE html>
<html>

    <head>
		<title>{%	block	title	%}{%	endblock	%}</title>
		<link	href="{%	static	"css/blog.css"	%}"	rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Blog App</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">About</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Policy</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
		<div	id="content">
			</div>
			<div	id="sidebar">
		</div>

		{% block content %}
			
		{% endblock content %}
		<footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Copyright &copy; Shudhanshu Jaiswal</p>
        </footer>
    </body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html"	%}
                {%	block	title	%}{{	post.title	}}{%	endblock	%}
                {%	block	content	%}
                <div class="container">
                  <div class="row">
                   <div class="col-md-8 card mb-4  mt-3 left  top">
                    <div class="card-body">
                        <h1>{{	post.title	}}</h1>
                        <p	class="date">
                        Published	{{	post.publish	}}	by	{{	post.author	}}
                        </p>
                                      <p class=" text-muted">{{	post.body|linebreaks	}}</p>
                                      <p class="card-text "></p>
                        <p>
                                <a      class="btn btn-primary"	href="{%	url	"blog:post_share"	post.id	%}">
                                        Share	this	post
                                </a>
                        </p>

                        {%	with	comments.count	as	total_comments	%}
                                        <h2>
                                                        {{	total_comments	}}	comment{{	total_comments|pluralize	}}
                                        </h2>
                        {%	endwith	%}
                        {%	for	comment	in	comments	%}
                        <div	class="comment">
                                <p	class="info">
                                        Comment	{{	forloop.counter	}}	by	{{	comment.name	}}
                                        {{	comment.created	}}
                                </p>
                                {{	comment.body|linebreaks	}}
                        </div>
                        {%	empty	%}
                        <p>There	are	no	comments	yet.</p>
                        {%	endfor	%}
                        {%	if	new_comment	%}
                                <h2>Your	comment	has	been	added.</h2>
                        {%	else	%}
                        <h2>Add	a	new	comment</h2>
                        <form class="farm"	action="."	method="post">
                                {{	comment_form.as_p	}}
                                {%	csrf_token	%}
                                <p><input       class="btn btn-primary"	type="submit"	value="Add comment"></p>
                        </form>
                        {%	endif	%}
                     </div>
                    </div>
                    {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
                  </div>
                </div>

{%	endblock	%}

blog/templates/blog/post/list.html
{%	extends	"blog/base.html"	%}
{%	block	title	%}My	Blog{%	endblock	%}
{%	block	content	%}
<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                    <p class="text-light">We Love Django As much as you do..! &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {%	for	post	in	posts	%}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">Published	{{	post.publish	}}	by	{{	post.author	}} </p>
                    <p class="card-text">{{	post.body|truncatewords:30|linebreaks	}}</p>
                    <a href="{{	post.get_absolute_url	}}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
			{%	include	"pagination.html"	with    page=page_obj	%}
        </div>
        {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%	endblock	%}

blog/templates/blog/post/share.html
{%	extends	"blog/base.html"	%}
{%	block	title	%}Share	a	post{%	endblock	%}
{%	block	content	%}
<div class="container">
	<div class="row">
	  <div class="col-md-8 card mb-4  mt-3 left  top">
		<div class="card-body">
			{%	if	sent	%}
					<h1>E-mail	successfully	sent</h1>
					<p>
							"{{	post.title	}}"	was	successfully	sent	to	{{	form.cleaned_data.to	}}.
					</p>
			{%	else	%}
					<h1>Share	"{{	post.title	}}"	by	e-mail</h1>
					<form	class="farm" action="."	method="post">

									{{	form.as_p	}}
									{%	csrf_token	%}
					<input	type="submit"	class="btn btn-primary"	value="Send	e-mail">
					</form>
			{%	endif	%}
	    </div>
	  </div>
	  {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%	endblock	%}

blog/templates/blog/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
        <a href="#"
           class="btn btn-danger">Know more!</a>
    </div>
</div>
</div>

{% endblock sidebar %}

blog/templates/pagination.html
<div	class="pagination">
	<span	class="step-links">
	{%	if	page.has_previous	%}
	<a	href="?page={{	page.previous_page_number	}}"	class="btn btn-primary">Previous</a>
	{%	endif	%}
	<span	class="current">
	Page	{{	page.number	}}	of	{{	page.paginator.num_pages	}}.
	</span>
	{%	if	page.has_next	%}
	<a	href="?page={{	page.next_page_number	}}"	class="btn btn-primary">Next</a>
	{%	endif	%}
		</span>
</div>